baseURL = "https://w3nch.github.io/"
languageCode = "en-us"
title = "Hello w3nch"
theme = "terminal"
paginate = 10

[markup.goldmark.renderer]
  unsafe = true

[markup.highlight]
  noClasses = false

[markup.tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false

[params]
  contentTypeName = "posts"
  showMenuItems = 10
  fullWidthTheme = false
  centerTheme = true
  autoCover = true
  showLastUpdated = false
  defaultTheme = "dark"
  enableThemeToggle = true
  customCSS = ["css/code.css", "css/writeups.css"]
  homeTitle = "Hello, Friend."
  homeSubtitle = "Breaking things to understand them."
  googleSiteVerification = "Y0vKmSo2ywuZMtkvsVA7iEgOgXMqrmSRhHQXOK9E3NM"
  customHead = '<meta name="google-site-verification" content="Y0vKmSo2ywuZMtkvsVA7iEgOgXMqrmSRhHQXOK9E3NM" />'

  [params.logo]
    logoText = "hello ;)"
    logoHomeLink = "/"

[params.footer]
  copyright = "© 1337 w3nch"
  author = true
  bottomText = [
    "Powered by Hugo"
  ]

[taxonomies]
  tag = "tags"
  category = "categories"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[languages]
  [languages.en]
    languageName = "English"
    title = "Hello w3nch"
    copyright = "© 1337 w3nch"

    [languages.en.params]
      subtitle = "Breaking things to understand them."
      keywords = ""
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"
      minuteReadingTime = "min read"
      words = "words"

      [languages.en.params.logo]
        logoText = "hello ;)"
        logoHomeLink = "/"

      [languages.en.menu]
        [[languages.en.menu.main]]
          identifier = "blog"
          name = "Blog"
          url = "/posts/"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "about"
          name = "About"
          url = "/about/"
          weight = 2

        [[languages.en.menu.main]]
          identifier = "contact"
          name = "Contact"
          url = "/contact/"
          weight = 3

        [[languages.en.menu.main]]
          identifier = "resume"
          name = "Resume"
          url = "/resume.pdf"
          weight = 4

        [[languages.en.menu.main]]
          identifier = "writeups"
          name = "Writeup"
          url = "/writeups/"
          weight = 5